//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoxyMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoxyMonitor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string AccountsText {
            get {
                return ResourceManager.GetString("AccountsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Account.
        /// </summary>
        public static string AddAccountText {
            get {
                return ResourceManager.GetString("AddAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        public static string AlertsText {
            get {
                return ResourceManager.GetString("AlertsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] app {
            get {
                object obj = ResourceManager.GetObject("app", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Effort.
        /// </summary>
        public static string AverageEffortText {
            get {
                return ResourceManager.GetString("AverageEffortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collateral Balance.
        /// </summary>
        public static string CollateralBalanceText {
            get {
                return ResourceManager.GetString("CollateralBalanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty.
        /// </summary>
        public static string DifficultyText {
            get {
                return ResourceManager.GetString("DifficultyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution Ratio.
        /// </summary>
        public static string DistributionRatioText {
            get {
                return ResourceManager.GetString("DistributionRatioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Capacity History 24h.
        /// </summary>
        public static string ECHistoryChartHeaderText {
            get {
                return ResourceManager.GetString("ECHistoryChartHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Capacity.
        /// </summary>
        public static string EstimatedCapacityText {
            get {
                return ResourceManager.GetString("EstimatedCapacityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est Daily Reward.
        /// </summary>
        public static string EstimatedDailyRewardText {
            get {
                return ResourceManager.GetString("EstimatedDailyRewardText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Partial Accepted.
        /// </summary>
        public static string LastPartialAcceptedText {
            get {
                return ResourceManager.GetString("LastPartialAcceptedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Payout In.
        /// </summary>
        public static string NextPayoutText {
            get {
                return ResourceManager.GetString("NextPayoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string OpenAboutText {
            get {
                return ResourceManager.GetString("OpenAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string OpenAccountsText {
            get {
                return ResourceManager.GetString("OpenAccountsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string OpenSettingsText {
            get {
                return ResourceManager.GetString("OpenSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Balance.
        /// </summary>
        public static string PendingBalanceText {
            get {
                return ResourceManager.GetString("PendingBalanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares History 24h.
        /// </summary>
        public static string SharesHistoryChartHeaderText {
            get {
                return ResourceManager.GetString("SharesHistoryChartHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Netspace.
        /// </summary>
        public static string TotalNetspaceText {
            get {
                return ResourceManager.GetString("TotalNetspaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated: {0:T}.
        /// </summary>
        public static string UpdatedStringFormat {
            get {
                return ResourceManager.GetString("UpdatedStringFormat", resourceCulture);
            }
        }
    }
}
